import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography, Input } from "antd";
import { useState } from "react";

const { Title, Paragraph, Text, Link } = Typography;

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography.Title>Base64 Encode / Decode</Typography.Title>

        <Input.TextArea placeholder="인코딩할 문자 입력"></Input.TextArea>
      </main>
    </>
  );
}
