import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Typography, Input, Layout, Button, Space } from "antd";
import { useState } from "react";

const { Title, Paragraph, Text, Link } = Typography;

const inter = Inter({ subsets: ["latin"] });

function encodeToBase64(text: string) {
  const utf8Bytes = new TextEncoder().encode(text);

  const base64Encoded = btoa(
    String.fromCharCode.apply(null, Array.from(utf8Bytes))
  );

  return base64Encoded;
}

function decodeFromBase64(base64Encoded: string) {
  const utf8Bytes = new Uint8Array(
    atob(base64Encoded)
      .split("")
      .map((char) => char.charCodeAt(0))
  );

  const decodedText = new TextDecoder().decode(utf8Bytes);

  return decodedText;
}

export default function Home() {
  const [encodeValue, setEncodeValue] = useState("");
  const [encodeResult, setEncodeResult] = useState("");

  const [decodeValue, setDecodeValue] = useState("");
  const [decodeResult, setDecodeResult] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="App"
        style={{
          height: "100vh",
        }}
      >
        <Layout>
          <Layout.Content>
            <Typography.Title>Base64 Encode / Decode</Typography.Title>

            <Space
              size="middle"
              direction="vertical"
              style={{
                width: "40%",
                height: "100vh",
              }}
            >
              <Input.TextArea
                placeholder="Encoding data"
                value={encodeValue}
                onChange={(event) => setEncodeValue(event.target.value)}
              />

              <Input.TextArea placeholder="Result" value={encodeResult} />

              <Button
                onClick={() => {
                  setEncodeResult(encodeToBase64(encodeValue));
                }}
              >
                Convert
              </Button>

              <Button
                onClick={() => {
                  navigator.clipboard.writeText(encodeResult);
                }}
              >
                Copy to clipboard
              </Button>
            </Space>

            {/* <div style={{ width: "10px" }}></div> */}

            <Space
              size="middle"
              direction="vertical"
              style={{
                width: "40%",
                height: "100vh",
              }}
            >
              <Input.TextArea
                placeholder="Decode data"
                value={decodeValue}
                onChange={(event) => setDecodeValue(event.target.value)}
              />

              <Input.TextArea placeholder="Result" value={decodeResult} />

              <Button
                onClick={() => {
                  setDecodeResult(decodeFromBase64(decodeValue));
                }}
              >
                Convert
              </Button>

              <Button
                onClick={() => {
                  navigator.clipboard.writeText(decodeResult);
                }}
              >
                Copy to clipboard
              </Button>
            </Space>
          </Layout.Content>
        </Layout>
      </main>
    </>
  );
}
